version: '3.7'

services:
    mongo:
        image: mongo:4.2.20
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: mpw
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
            - ./ops/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#            - ./data/ops/configs/mongo/mongod.conf:/etc/mongod.conf
#            - ./data/ops/configs/mongo/keyfile:/etc/mongod.keyfile
#        command: mongod --config /etc/mongod.conf

    jenkins:
        image: jenkins:2.60.3
        restart: always
        ports:
            - 8003:8080
            - 50000:50000
        volumes:
            - jenkins:/var/jenkins_home

volumes:
    mongo:
        driver: local
    jenkins:
        driver: local