#!/bin/sh

if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

if [ "$1" = 'php-fpm' ] || [ "$1" = 'php' ] || [ "$1" = 'bin/console' ]; then
    mkdir -p var/cache var/log

    php ./bin/console cache:warm -n -e $APP_ENV
fi

rm /usr/local/etc/php-fpm.d/zz-docker.conf

php-fpm -D
nginx -g "daemon off;"